trigger: none
pr: none

schedules:
- cron: "45 23 * * *"
  displayName: Nightly maintenance
  branches:
    include:
    - main
  always: true

variables:
  - group: MaintenanceSecrets

jobs:
- job:
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'
      projects: HaroohieCloudManager/HaroohieCloudManager.csproj
      arguments: '-- check-cors-proxy -o "https://haroohie.club" -d "$(DiscordWebhook)" -c "https://cors.haroohie.club/https://github.com/haroohie-club/ChokuretsuTranslationRelease/releases/download/en-v0.6/chokuretsu-patch-en-v0.6-subbedoped-voicesubs.xdelta"'
    displayName: Check CORS proxy
  displayName: Check CORS proxy
- job:
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'
      projects: HaroohieCloudManager/HaroohieCloudManager.csproj
      arguments: '-- update-weblate -k $(WeblateApiKey) -p https://weblate.haroohie.club/api/projects/suzumiya-haruhi-no-chokuretsu/'
    displayName: Update Chokuretsu Weblate
  displayName: Update Chokuretsu Weblate
- job:  
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'
      projects: HaroohieCloudManager/HaroohieCloudManager.csproj
      arguments: '-- update-weblate -k $(WeblateApiKey) -p https://weblate.haroohie.club/api/projects/suzumiya-haruhi-no-heiretsu/'
    displayName: Update Heiretsu Weblate
  displayName: Update Heiretsu Weblate